[package]
name = "oxidmol-render"
version = "0.1.0"
edition = "2021"

[lib]
name = "oxidmol_render"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
# graphics
wgpu = "25.0.2"
raw-window-handle = "0.6.2"
pollster = "0.4.0"
# chemistry
pdbtbx = "0.11"
# error handling
thiserror = "2.0.16"
# math
glam = "0.30.7"
# logger
log = "0.4.28"
env_logger = "0.11.8"
# timer
chrono = "0.4.42"

[dev-dependencies]
approx = "0.5.1"
