[changelog]
header = "# Changelog\n"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/ye11owSub/oxidmol/commit/{{ commit.id }}))\
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false

commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^refactor", group = "Refactor" },
    { message = "^perf", group = "Performance" },
    { message = "^revert", group = "Reverts" },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore", skip = true },
    { message = "^docs", skip = true },
    { message = "^ci", skip = true },
    { message = "^test", skip = true },
    { message = "^style", skip = true },
]

filter_commits = true
tag_pattern = "v[0-9].*"
