from __future__ import annotations

from typing import Any, Self

class WgpuRenderer:
    def __init__(self, window_handle: int, width: int = 800, height: int = 600) -> None: ...
    def render(self) -> None: ...
    def resize(self, width: int, height: int) -> None: ...
    def load_molecule(self, path: str) -> None: ...
    def load_molecule_obj(self, mol: Molecule) -> None: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...

class Molecule:
    @classmethod
    def from_cif(cls, path: str) -> Self: ...
    @classmethod
    def from_pdb(cls, path: str) -> Self: ...
    @classmethod
    def from_str(cls, content: str) -> Self: ...
    def name(self) -> str | None: ...

def get_backend_info() -> dict[str, Any]: ...
def create_shader_from_file(path: str) -> str: ...

__version__: str
__author__: str
__description__: str
