use crate::utils::UnknownElement;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Element {
    H,
    He,
    Li,
    Be,
    B,
    C,
    N,
    O,
    F,
    Ne,
    Na,
    Mg,
    Al,
    Si,
    P,
    S,
    Cl,
    Ar,
    K,
    Ca,
    Sc,
    Ti,
    V,
    Cr,
    Mn,
    Fe,
    Co,
    Ni,
    Cu,
    Zn,
    Ga,
    Ge,
    As,
    Se,
    Br,
    Kr,
    Rb,
    Sr,
    Y,
    Zr,
    Nb,
    Mo,
    Tc,
    Ru,
    Rh,
    Pd,
    Ag,
    Cd,
    In,
    Sn,
    Sb,
    Te,
    I,
    Xe,
    Cs,
    Ba,
    La,
    Ce,
    Pr,
    Nd,
    Pm,
    Sm,
    Eu,
    Gd,
    Tb,
    Dy,
    Ho,
    Er,
    Tm,
    Yb,
    Lu,
    Hf,
    Ta,
    W,
    Re,
    Os,
    Ir,
    Pt,
    Au,
    Hg,
    Tl,
    Pb,
    Bi,
    Po,
    At,
    Rn,
    Fr,
    Ra,
    Ac,
    Th,
    Pa,
    U,
    Np,
    Pu,
    Am,
    Cm,
    Bk,
    Cf,
    Es,
    Fm,
    Md,
    No,
    Lr,
    Rf,
    Db,
    Sg,
    Bh,
    Hs,
    Mt,
    Ds,
    Rg,
    Cn,
    Nh,
    Fl,
    Mc,
    Lv,
    Ts,
    Og,
    Unknown,
}

impl std::str::FromStr for Element {
    type Err = UnknownElement;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let trimmed = s.trim();
        Ok(match trimmed {
            "H" => Self::H,
            "He" => Self::He,
            "Li" => Self::Li,
            "Be" => Self::Be,
            "B" => Self::B,
            "C" => Self::C,
            "N" => Self::N,
            "O" => Self::O,
            "F" => Self::F,
            "Ne" => Self::Ne,
            "Na" => Self::Na,
            "Mg" => Self::Mg,
            "Al" => Self::Al,
            "Si" => Self::Si,
            "P" => Self::P,
            "S" => Self::S,
            "Cl" => Self::Cl,
            "Ar" => Self::Ar,
            "K" => Self::K,
            "Ca" => Self::Ca,
            "Sc" => Self::Sc,
            "Ti" => Self::Ti,
            "V" => Self::V,
            "Cr" => Self::Cr,
            "Mn" => Self::Mn,
            "Fe" => Self::Fe,
            "Co" => Self::Co,
            "Ni" => Self::Ni,
            "Cu" => Self::Cu,
            "Zn" => Self::Zn,
            "Ga" => Self::Ga,
            "Ge" => Self::Ge,
            "As" => Self::As,
            "Se" => Self::Se,
            "Br" => Self::Br,
            "Kr" => Self::Kr,
            "Rb" => Self::Rb,
            "Sr" => Self::Sr,
            "Y" => Self::Y,
            "Zr" => Self::Zr,
            "Nb" => Self::Nb,
            "Mo" => Self::Mo,
            "Tc" => Self::Tc,
            "Ru" => Self::Ru,
            "Rh" => Self::Rh,
            "Pd" => Self::Pd,
            "Ag" => Self::Ag,
            "Cd" => Self::Cd,
            "In" => Self::In,
            "Sn" => Self::Sn,
            "Sb" => Self::Sb,
            "Te" => Self::Te,
            "I" => Self::I,
            "Xe" => Self::Xe,
            "Cs" => Self::Cs,
            "Ba" => Self::Ba,
            "La" => Self::La,
            "Ce" => Self::Ce,
            "Pr" => Self::Pr,
            "Nd" => Self::Nd,
            "Pm" => Self::Pm,
            "Sm" => Self::Sm,
            "Eu" => Self::Eu,
            "Gd" => Self::Gd,
            "Tb" => Self::Tb,
            "Dy" => Self::Dy,
            "Ho" => Self::Ho,
            "Er" => Self::Er,
            "Tm" => Self::Tm,
            "Yb" => Self::Yb,
            "Lu" => Self::Lu,
            "Hf" => Self::Hf,
            "Ta" => Self::Ta,
            "W" => Self::W,
            "Re" => Self::Re,
            "Os" => Self::Os,
            "Ir" => Self::Ir,
            "Pt" => Self::Pt,
            "Au" => Self::Au,
            "Hg" => Self::Hg,
            "Tl" => Self::Tl,
            "Pb" => Self::Pb,
            "Bi" => Self::Bi,
            "Po" => Self::Po,
            "At" => Self::At,
            "Rn" => Self::Rn,
            "Fr" => Self::Fr,
            "Ra" => Self::Ra,
            "Ac" => Self::Ac,
            "Th" => Self::Th,
            "Pa" => Self::Pa,
            "U" => Self::U,
            "Np" => Self::Np,
            "Pu" => Self::Pu,
            "Am" => Self::Am,
            "Cm" => Self::Cm,
            "Bk" => Self::Bk,
            "Cf" => Self::Cf,
            "Es" => Self::Es,
            "Fm" => Self::Fm,
            "Md" => Self::Md,
            "No" => Self::No,
            "Lr" => Self::Lr,
            "Rf" => Self::Rf,
            "Db" => Self::Db,
            "Sg" => Self::Sg,
            "Bh" => Self::Bh,
            "Hs" => Self::Hs,
            "Mt" => Self::Mt,
            "Ds" => Self::Ds,
            "Rg" => Self::Rg,
            "Cn" => Self::Cn,
            "Nh" => Self::Nh,
            "Fl" => Self::Fl,
            "Mc" => Self::Mc,
            "Lv" => Self::Lv,
            "Ts" => Self::Ts,
            "Og" => Self::Og,
            _ => return Err(UnknownElement(trimmed.to_string())),
        })
    }
}

impl Element {
    /// Van der Waals radius in Å.
    /// Source: Alvarez (2013) Dalton Trans. 42, 8617 — most complete set.
    /// Falls back to 1.80 Å for elements without measured data.
    pub fn vdw_radius(self) -> f32 {
        match self {
            Self::H => 1.20,
            Self::He => 1.43,
            Self::Li => 2.12,
            Self::Be => 1.98,
            Self::B => 1.91,
            Self::C => 1.77,
            Self::N => 1.66,
            Self::O => 1.50,
            Self::F => 1.46,
            Self::Ne => 1.58,
            Self::Na => 2.50,
            Self::Mg => 2.51,
            Self::Al => 2.25,
            Self::Si => 2.19,
            Self::P => 1.90,
            Self::S => 1.89,
            Self::Cl => 1.82,
            Self::Ar => 1.83,
            Self::K => 2.73,
            Self::Ca => 2.62,
            Self::Sc => 2.58,
            Self::Ti => 2.46,
            Self::V => 2.42,
            Self::Cr => 2.45,
            Self::Mn => 2.45,
            Self::Fe => 2.44,
            Self::Co => 2.40,
            Self::Ni => 2.40,
            Self::Cu => 2.38,
            Self::Zn => 2.39,
            Self::Ga => 2.32,
            Self::Ge => 2.29,
            Self::As => 1.88,
            Self::Se => 1.82,
            Self::Br => 1.86,
            Self::Kr => 2.25,
            Self::Rb => 3.21,
            Self::Sr => 2.84,
            Self::Y => 2.75,
            Self::Zr => 2.52,
            Self::Nb => 2.56,
            Self::Mo => 2.45,
            Self::Tc => 2.44,
            Self::Ru => 2.46,
            Self::Rh => 2.44,
            Self::Pd => 2.15,
            Self::Ag => 2.53,
            Self::Cd => 2.49,
            Self::In => 2.43,
            Self::Sn => 2.42,
            Self::Sb => 2.47,
            Self::Te => 1.99,
            Self::I => 2.04,
            Self::Xe => 2.06,
            Self::Cs => 3.48,
            Self::Ba => 3.03,
            Self::La => 2.98,
            Self::Ce => 2.88,
            Self::Pr => 2.92,
            Self::Nd => 2.95,
            Self::Pm => 2.90,
            Self::Sm => 2.87,
            Self::Eu => 2.83,
            Self::Gd => 2.79,
            Self::Tb => 2.87,
            Self::Dy => 2.81,
            Self::Ho => 2.83,
            Self::Er => 2.79,
            Self::Tm => 2.87,
            Self::Yb => 2.80,
            Self::Lu => 2.74,
            Self::Hf => 2.63,
            Self::Ta => 2.53,
            Self::W => 2.57,
            Self::Re => 2.49,
            Self::Os => 2.48,
            Self::Ir => 2.41,
            Self::Pt => 2.29,
            Self::Au => 2.32,
            Self::Hg => 2.45,
            Self::Tl => 2.47,
            Self::Pb => 2.60,
            Self::Bi => 2.54,
            Self::Po => 2.50,
            Self::At => 2.50,
            Self::Rn => 2.20,
            _ => 1.80,
        }
    }

    /// CPK color as linear RGB [0..1].
    /// Follows the Jmol/RASMOL standard widely used in molecular viewers.
    pub fn cpk_color(self) -> [f32; 3] {
        match self {
            Self::H => [1.00, 1.00, 1.00],
            Self::He => [0.85, 1.00, 1.00],
            Self::Li => [0.80, 0.50, 1.00],
            Self::Be => [0.76, 1.00, 0.00],
            Self::B => [1.00, 0.71, 0.71],
            Self::C => [0.56, 0.56, 0.56],
            Self::N => [0.19, 0.31, 0.97],
            Self::O => [1.00, 0.05, 0.05],
            Self::F => [0.56, 0.88, 0.31],
            Self::Ne => [0.70, 0.89, 0.96],
            Self::Na => [0.67, 0.36, 0.95],
            Self::Mg => [0.54, 1.00, 0.00],
            Self::Al => [0.75, 0.65, 0.65],
            Self::Si => [0.94, 0.78, 0.63],
            Self::P => [1.00, 0.50, 0.00],
            Self::S => [1.00, 1.00, 0.19],
            Self::Cl => [0.12, 0.94, 0.12],
            Self::Ar => [0.50, 0.82, 0.89],
            Self::K => [0.56, 0.25, 0.83],
            Self::Ca => [0.24, 1.00, 0.00],
            Self::Sc => [0.90, 0.90, 0.90],
            Self::Ti => [0.75, 0.76, 0.78],
            Self::V => [0.65, 0.65, 0.67],
            Self::Cr => [0.54, 0.60, 0.78],
            Self::Mn => [0.61, 0.48, 0.78],
            Self::Fe => [0.88, 0.40, 0.20],
            Self::Co => [0.94, 0.56, 0.63],
            Self::Ni => [0.31, 0.82, 0.31],
            Self::Cu => [0.78, 0.50, 0.20],
            Self::Zn => [0.49, 0.50, 0.69],
            Self::Ga => [0.76, 0.56, 0.56],
            Self::Ge => [0.40, 0.56, 0.56],
            Self::As => [0.74, 0.50, 0.89],
            Self::Se => [1.00, 0.63, 0.00],
            Self::Br => [0.65, 0.16, 0.16],
            Self::Kr => [0.36, 0.72, 0.82],
            Self::Rb => [0.44, 0.18, 0.69],
            Self::Sr => [0.00, 1.00, 0.00],
            Self::Y => [0.58, 1.00, 1.00],
            Self::Zr => [0.58, 0.88, 0.88],
            Self::Nb => [0.45, 0.76, 0.79],
            Self::Mo => [0.33, 0.71, 0.71],
            Self::Tc => [0.23, 0.62, 0.62],
            Self::Ru => [0.14, 0.56, 0.56],
            Self::Rh => [0.04, 0.49, 0.55],
            Self::Pd => [0.00, 0.41, 0.52],
            Self::Ag => [0.75, 0.75, 0.75],
            Self::Cd => [1.00, 0.85, 0.56],
            Self::In => [0.65, 0.46, 0.45],
            Self::Sn => [0.40, 0.50, 0.50],
            Self::Sb => [0.62, 0.39, 0.71],
            Self::Te => [0.83, 0.48, 0.00],
            Self::I => [0.58, 0.00, 0.58],
            Self::Xe => [0.26, 0.62, 0.69],
            Self::Cs => [0.34, 0.09, 0.56],
            Self::Ba => [0.00, 0.79, 0.00],
            Self::La => [0.44, 0.83, 1.00],
            Self::Ce => [1.00, 1.00, 0.78],
            Self::Pr => [0.85, 1.00, 0.78],
            Self::Nd => [0.78, 1.00, 0.78],
            Self::Pm => [0.64, 1.00, 0.78],
            Self::Sm => [0.56, 1.00, 0.78],
            Self::Eu => [0.38, 1.00, 0.78],
            Self::Gd => [0.27, 1.00, 0.78],
            Self::Tb => [0.19, 1.00, 0.78],
            Self::Dy => [0.12, 1.00, 0.78],
            Self::Ho => [0.00, 1.00, 0.61],
            Self::Er => [0.00, 0.90, 0.46],
            Self::Tm => [0.00, 0.83, 0.32],
            Self::Yb => [0.00, 0.75, 0.22],
            Self::Lu => [0.00, 0.67, 0.14],
            Self::Hf => [0.30, 0.76, 1.00],
            Self::Ta => [0.30, 0.65, 1.00],
            Self::W => [0.13, 0.58, 0.84],
            Self::Re => [0.15, 0.49, 0.67],
            Self::Os => [0.15, 0.40, 0.59],
            Self::Ir => [0.09, 0.33, 0.53],
            Self::Pt => [0.82, 0.82, 0.88],
            Self::Au => [1.00, 0.82, 0.14],
            Self::Hg => [0.72, 0.72, 0.82],
            Self::Tl => [0.65, 0.33, 0.30],
            Self::Pb => [0.34, 0.35, 0.38],
            Self::Bi => [0.62, 0.31, 0.71],
            Self::Po => [0.67, 0.36, 0.00],
            Self::At => [0.46, 0.31, 0.27],
            Self::Rn => [0.26, 0.51, 0.59],
            Self::Fr => [0.26, 0.00, 0.40],
            Self::Ra => [0.00, 0.49, 0.00],
            Self::Ac => [0.44, 0.67, 0.98],
            Self::Th => [0.00, 0.73, 1.00],
            Self::Pa => [0.00, 0.63, 1.00],
            Self::U => [0.00, 0.56, 1.00],
            Self::Np => [0.00, 0.50, 1.00],
            Self::Pu => [0.00, 0.42, 1.00],
            Self::Am => [0.33, 0.36, 0.95],
            Self::Cm => [0.47, 0.36, 0.89],
            Self::Bk => [0.54, 0.31, 0.89],
            Self::Cf => [0.63, 0.21, 0.83],
            Self::Es => [0.70, 0.12, 0.83],
            Self::Fm => [0.70, 0.12, 0.73],
            Self::Md => [0.70, 0.05, 0.65],
            Self::No => [0.74, 0.05, 0.53],
            Self::Lr => [0.78, 0.00, 0.40],
            _ => [0.80, 0.80, 0.80],
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_common_elements() {
        assert_eq!("C".parse::<Element>().unwrap(), Element::C);
        assert_eq!("N".parse::<Element>().unwrap(), Element::N);
        assert_eq!("O".parse::<Element>().unwrap(), Element::O);
        assert_eq!("Fe".parse::<Element>().unwrap(), Element::Fe);
        assert_eq!("Se".parse::<Element>().unwrap(), Element::Se);
        assert_eq!("  H  ".parse::<Element>().unwrap(), Element::H);
    }

    #[test]
    fn test_parse_unknown_returns_err() {
        assert!("X".parse::<Element>().is_err());
        assert!("Xx".parse::<Element>().is_err());

        let error = UnknownElement("Xx".to_string());
        assert_eq!(
            "Xx".parse::<Element>().unwrap_err().to_string(),
            error.to_string()
        );
    }

    #[test]
    fn test_vdw_radii_positive() {
        for elem in [
            Element::H,
            Element::C,
            Element::N,
            Element::O,
            Element::Fe,
            Element::Se,
        ] {
            assert!(elem.vdw_radius() > 0.0);
        }
    }

    #[test]
    fn test_cpk_colors_in_range() {
        for elem in [
            Element::H,
            Element::C,
            Element::N,
            Element::O,
            Element::S,
            Element::Fe,
        ] {
            let [r, g, b] = elem.cpk_color();
            assert!((0.0..=1.0).contains(&r));
            assert!((0.0..=1.0).contains(&g));
            assert!((0.0..=1.0).contains(&b));
        }
    }
}
