from typing import Any, Self

class PyWgpuRenderer:
    def __init__(self, window_handle: int, width: int = 800, height: int = 600) -> None: ...
    def render(self) -> None: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...

class Molecule:
    def __init__(self) -> None: ...
    @classmethod
    def from_cif(cls, path: str) -> Self: ...
    @classmethod
    def from_pdb(cls, path: str) -> Self: ...
    @classmethod
    def from_cif_str(cls, path: str) -> Self: ...

def get_backend_info() -> dict[str, Any]: ...
def create_shader_from_file(path: str) -> str: ...

__version__: str
__author__: str
__description__: str
