from typing import Any

class PyWgpuRenderer:
    def __init__(self, window_handle: int, width: int, height: int) -> None: ...
    def render(self) -> None: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...

def get_backend_info() -> dict[str, Any]: ...
def create_shader_from_file(path: str) -> str: ...

__version__: str
__author__: str
__description__: str
